---
- name: playbook, install nginx
  hosts: all
  vars:
    nginx:
        worker_processes: 10
        worker_connections: 512
        log_dir: /var/log/nginx
        log_file: access.log
        port: 80
  tasks:
    - name: install, epel-release
      yum:
        name: epel-release
        state: latest
        update_cache: yes

    - name: install nginx
      yum:
        name: nginx
        state: latest
        update_cache: yes

    - name: config, nginx.conf
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        force: yes

    - name: start, enable nginx
      service:
        name: nginx
        state: started
        enabled: yes